---

- name: Install required packages
  become: true
  ansible.builtin.package:
    name: "{{ libvirt_kvm_required_packages[ansible_facts.os_family | lower] | flatten(1) }}"
    state: present
    update_cache: true

- name: Include libvirt setup
  ansible.builtin.include_tasks:
    file: libvirt.yml

- name: Include vm setup
  loop: "{{ libvirt_kvm_machines }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  ansible.builtin.include_tasks:
    file: vm_setup.yml

...
